FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci

# The .env.production file is generated by Cloud Build BEFORE Docker starts
# and is copied in the next step. Vite picks it up automatically.
COPY . .
RUN npm run build

# Serve built files via nginx on port 8080 (Cloud Run default)
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
